//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OctoStyle.Core.Tests.Integration {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class FileContents {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FileContents() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OctoStyle.Core.Tests.Integration.FileContents", typeof(FileContents).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to diff --git a/src/TestLibrary/TestLibrary.csproj b/src/TestLibrary/TestLibrary.csproj
        ///index e29f3ed..47c7471 100644
        ///--- a/src/TestLibrary/TestLibrary.csproj
        ///+++ b/src/TestLibrary/TestLibrary.csproj
        ///@@ -30,13 +30,12 @@
        ///     &lt;WarningLevel&gt;4&lt;/WarningLevel&gt;
        ///   &lt;/PropertyGroup&gt;
        ///   &lt;ItemGroup&gt;
        ///+    &lt;Compile Include=&quot;Nested\TestClass3.cs&quot; /&gt;
        ///     &lt;Compile Include=&quot;Properties\AssemblyInfo.cs&quot; /&gt;
        ///     &lt;Compile Include=&quot;TestClass.cs&quot; /&gt;
        ///-    &lt;Compile Include=&quot;TestClass2.cs&quot; /&gt;
        ///-  &lt;/ItemGroup&gt;
        ///-  &lt;ItemGroup&gt;
        ///-    &lt;Fold [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TestLibraryCsprojDiff {
            get {
                return ResourceManager.GetString("TestLibraryCsprojDiff", resourceCulture);
            }
        }
    }
}
